# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sanda/Desktop/ViennaCL-1.1.2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sanda/Desktop/ViennaCL-1.1.2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sanda/Desktop/ViennaCL-1.1.2/CMakeFiles /home/sanda/Desktop/ViennaCL-1.1.2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sanda/Desktop/ViennaCL-1.1.2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blas1

# Build rule for target.
blas1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blas1
.PHONY : blas1

# fast build rule for target.
blas1/fast:
	$(MAKE) -f CMakeFiles/blas1.dir/build.make CMakeFiles/blas1.dir/build
.PHONY : blas1/fast

#=============================================================================
# Target rules for targets named blas3bench

# Build rule for target.
blas3bench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blas3bench
.PHONY : blas3bench

# fast build rule for target.
blas3bench/fast:
	$(MAKE) -f CMakeFiles/blas3bench.dir/build.make CMakeFiles/blas3bench.dir/build
.PHONY : blas3bench/fast

#=============================================================================
# Target rules for targets named custom-context

# Build rule for target.
custom-context: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 custom-context
.PHONY : custom-context

# fast build rule for target.
custom-context/fast:
	$(MAKE) -f CMakeFiles/custom-context.dir/build.make CMakeFiles/custom-context.dir/build
.PHONY : custom-context/fast

#=============================================================================
# Target rules for targets named custom-kernels

# Build rule for target.
custom-kernels: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 custom-kernels
.PHONY : custom-kernels

# fast build rule for target.
custom-kernels/fast:
	$(MAKE) -f CMakeFiles/custom-kernels.dir/build.make CMakeFiles/custom-kernels.dir/build
.PHONY : custom-kernels/fast

#=============================================================================
# Target rules for targets named matrixparams

# Build rule for target.
matrixparams: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrixparams
.PHONY : matrixparams

# fast build rule for target.
matrixparams/fast:
	$(MAKE) -f CMakeFiles/matrixparams.dir/build.make CMakeFiles/matrixparams.dir/build
.PHONY : matrixparams/fast

#=============================================================================
# Target rules for targets named openclbench

# Build rule for target.
openclbench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openclbench
.PHONY : openclbench

# fast build rule for target.
openclbench/fast:
	$(MAKE) -f CMakeFiles/openclbench.dir/build.make CMakeFiles/openclbench.dir/build
.PHONY : openclbench/fast

#=============================================================================
# Target rules for targets named parameter_reader

# Build rule for target.
parameter_reader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parameter_reader
.PHONY : parameter_reader

# fast build rule for target.
parameter_reader/fast:
	$(MAKE) -f CMakeFiles/parameter_reader.dir/build.make CMakeFiles/parameter_reader.dir/build
.PHONY : parameter_reader/fast

#=============================================================================
# Target rules for targets named sparseparams

# Build rule for target.
sparseparams: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sparseparams
.PHONY : sparseparams

# fast build rule for target.
sparseparams/fast:
	$(MAKE) -f CMakeFiles/sparseparams.dir/build.make CMakeFiles/sparseparams.dir/build
.PHONY : sparseparams/fast

#=============================================================================
# Target rules for targets named vectorbench

# Build rule for target.
vectorbench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vectorbench
.PHONY : vectorbench

# fast build rule for target.
vectorbench/fast:
	$(MAKE) -f CMakeFiles/vectorbench.dir/build.make CMakeFiles/vectorbench.dir/build
.PHONY : vectorbench/fast

#=============================================================================
# Target rules for targets named vectorparams

# Build rule for target.
vectorparams: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vectorparams
.PHONY : vectorparams

# fast build rule for target.
vectorparams/fast:
	$(MAKE) -f CMakeFiles/vectorparams.dir/build.make CMakeFiles/vectorparams.dir/build
.PHONY : vectorparams/fast

#=============================================================================
# Target rules for targets named viennacl-info

# Build rule for target.
viennacl-info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 viennacl-info
.PHONY : viennacl-info

# fast build rule for target.
viennacl-info/fast:
	$(MAKE) -f CMakeFiles/viennacl-info.dir/build.make CMakeFiles/viennacl-info.dir/build
.PHONY : viennacl-info/fast

examples/benchmarks/blas3.o: examples/benchmarks/blas3.cpp.o
.PHONY : examples/benchmarks/blas3.o

# target to build an object file
examples/benchmarks/blas3.cpp.o:
	$(MAKE) -f CMakeFiles/blas3bench.dir/build.make CMakeFiles/blas3bench.dir/examples/benchmarks/blas3.cpp.o
.PHONY : examples/benchmarks/blas3.cpp.o

examples/benchmarks/blas3.i: examples/benchmarks/blas3.cpp.i
.PHONY : examples/benchmarks/blas3.i

# target to preprocess a source file
examples/benchmarks/blas3.cpp.i:
	$(MAKE) -f CMakeFiles/blas3bench.dir/build.make CMakeFiles/blas3bench.dir/examples/benchmarks/blas3.cpp.i
.PHONY : examples/benchmarks/blas3.cpp.i

examples/benchmarks/blas3.s: examples/benchmarks/blas3.cpp.s
.PHONY : examples/benchmarks/blas3.s

# target to generate assembly for a file
examples/benchmarks/blas3.cpp.s:
	$(MAKE) -f CMakeFiles/blas3bench.dir/build.make CMakeFiles/blas3bench.dir/examples/benchmarks/blas3.cpp.s
.PHONY : examples/benchmarks/blas3.cpp.s

examples/benchmarks/opencl.o: examples/benchmarks/opencl.cpp.o
.PHONY : examples/benchmarks/opencl.o

# target to build an object file
examples/benchmarks/opencl.cpp.o:
	$(MAKE) -f CMakeFiles/openclbench.dir/build.make CMakeFiles/openclbench.dir/examples/benchmarks/opencl.cpp.o
.PHONY : examples/benchmarks/opencl.cpp.o

examples/benchmarks/opencl.i: examples/benchmarks/opencl.cpp.i
.PHONY : examples/benchmarks/opencl.i

# target to preprocess a source file
examples/benchmarks/opencl.cpp.i:
	$(MAKE) -f CMakeFiles/openclbench.dir/build.make CMakeFiles/openclbench.dir/examples/benchmarks/opencl.cpp.i
.PHONY : examples/benchmarks/opencl.cpp.i

examples/benchmarks/opencl.s: examples/benchmarks/opencl.cpp.s
.PHONY : examples/benchmarks/opencl.s

# target to generate assembly for a file
examples/benchmarks/opencl.cpp.s:
	$(MAKE) -f CMakeFiles/openclbench.dir/build.make CMakeFiles/openclbench.dir/examples/benchmarks/opencl.cpp.s
.PHONY : examples/benchmarks/opencl.cpp.s

examples/benchmarks/vector.o: examples/benchmarks/vector.cpp.o
.PHONY : examples/benchmarks/vector.o

# target to build an object file
examples/benchmarks/vector.cpp.o:
	$(MAKE) -f CMakeFiles/vectorbench.dir/build.make CMakeFiles/vectorbench.dir/examples/benchmarks/vector.cpp.o
.PHONY : examples/benchmarks/vector.cpp.o

examples/benchmarks/vector.i: examples/benchmarks/vector.cpp.i
.PHONY : examples/benchmarks/vector.i

# target to preprocess a source file
examples/benchmarks/vector.cpp.i:
	$(MAKE) -f CMakeFiles/vectorbench.dir/build.make CMakeFiles/vectorbench.dir/examples/benchmarks/vector.cpp.i
.PHONY : examples/benchmarks/vector.cpp.i

examples/benchmarks/vector.s: examples/benchmarks/vector.cpp.s
.PHONY : examples/benchmarks/vector.s

# target to generate assembly for a file
examples/benchmarks/vector.cpp.s:
	$(MAKE) -f CMakeFiles/vectorbench.dir/build.make CMakeFiles/vectorbench.dir/examples/benchmarks/vector.cpp.s
.PHONY : examples/benchmarks/vector.cpp.s

examples/parameters/matrix.o: examples/parameters/matrix.cpp.o
.PHONY : examples/parameters/matrix.o

# target to build an object file
examples/parameters/matrix.cpp.o:
	$(MAKE) -f CMakeFiles/matrixparams.dir/build.make CMakeFiles/matrixparams.dir/examples/parameters/matrix.cpp.o
.PHONY : examples/parameters/matrix.cpp.o

examples/parameters/matrix.i: examples/parameters/matrix.cpp.i
.PHONY : examples/parameters/matrix.i

# target to preprocess a source file
examples/parameters/matrix.cpp.i:
	$(MAKE) -f CMakeFiles/matrixparams.dir/build.make CMakeFiles/matrixparams.dir/examples/parameters/matrix.cpp.i
.PHONY : examples/parameters/matrix.cpp.i

examples/parameters/matrix.s: examples/parameters/matrix.cpp.s
.PHONY : examples/parameters/matrix.s

# target to generate assembly for a file
examples/parameters/matrix.cpp.s:
	$(MAKE) -f CMakeFiles/matrixparams.dir/build.make CMakeFiles/matrixparams.dir/examples/parameters/matrix.cpp.s
.PHONY : examples/parameters/matrix.cpp.s

examples/parameters/parameter_reader.o: examples/parameters/parameter_reader.cpp.o
.PHONY : examples/parameters/parameter_reader.o

# target to build an object file
examples/parameters/parameter_reader.cpp.o:
	$(MAKE) -f CMakeFiles/parameter_reader.dir/build.make CMakeFiles/parameter_reader.dir/examples/parameters/parameter_reader.cpp.o
.PHONY : examples/parameters/parameter_reader.cpp.o

examples/parameters/parameter_reader.i: examples/parameters/parameter_reader.cpp.i
.PHONY : examples/parameters/parameter_reader.i

# target to preprocess a source file
examples/parameters/parameter_reader.cpp.i:
	$(MAKE) -f CMakeFiles/parameter_reader.dir/build.make CMakeFiles/parameter_reader.dir/examples/parameters/parameter_reader.cpp.i
.PHONY : examples/parameters/parameter_reader.cpp.i

examples/parameters/parameter_reader.s: examples/parameters/parameter_reader.cpp.s
.PHONY : examples/parameters/parameter_reader.s

# target to generate assembly for a file
examples/parameters/parameter_reader.cpp.s:
	$(MAKE) -f CMakeFiles/parameter_reader.dir/build.make CMakeFiles/parameter_reader.dir/examples/parameters/parameter_reader.cpp.s
.PHONY : examples/parameters/parameter_reader.cpp.s

examples/parameters/sparse.o: examples/parameters/sparse.cpp.o
.PHONY : examples/parameters/sparse.o

# target to build an object file
examples/parameters/sparse.cpp.o:
	$(MAKE) -f CMakeFiles/sparseparams.dir/build.make CMakeFiles/sparseparams.dir/examples/parameters/sparse.cpp.o
.PHONY : examples/parameters/sparse.cpp.o

examples/parameters/sparse.i: examples/parameters/sparse.cpp.i
.PHONY : examples/parameters/sparse.i

# target to preprocess a source file
examples/parameters/sparse.cpp.i:
	$(MAKE) -f CMakeFiles/sparseparams.dir/build.make CMakeFiles/sparseparams.dir/examples/parameters/sparse.cpp.i
.PHONY : examples/parameters/sparse.cpp.i

examples/parameters/sparse.s: examples/parameters/sparse.cpp.s
.PHONY : examples/parameters/sparse.s

# target to generate assembly for a file
examples/parameters/sparse.cpp.s:
	$(MAKE) -f CMakeFiles/sparseparams.dir/build.make CMakeFiles/sparseparams.dir/examples/parameters/sparse.cpp.s
.PHONY : examples/parameters/sparse.cpp.s

examples/parameters/vector.o: examples/parameters/vector.cpp.o
.PHONY : examples/parameters/vector.o

# target to build an object file
examples/parameters/vector.cpp.o:
	$(MAKE) -f CMakeFiles/vectorparams.dir/build.make CMakeFiles/vectorparams.dir/examples/parameters/vector.cpp.o
.PHONY : examples/parameters/vector.cpp.o

examples/parameters/vector.i: examples/parameters/vector.cpp.i
.PHONY : examples/parameters/vector.i

# target to preprocess a source file
examples/parameters/vector.cpp.i:
	$(MAKE) -f CMakeFiles/vectorparams.dir/build.make CMakeFiles/vectorparams.dir/examples/parameters/vector.cpp.i
.PHONY : examples/parameters/vector.cpp.i

examples/parameters/vector.s: examples/parameters/vector.cpp.s
.PHONY : examples/parameters/vector.s

# target to generate assembly for a file
examples/parameters/vector.cpp.s:
	$(MAKE) -f CMakeFiles/vectorparams.dir/build.make CMakeFiles/vectorparams.dir/examples/parameters/vector.cpp.s
.PHONY : examples/parameters/vector.cpp.s

examples/tutorial/blas1.o: examples/tutorial/blas1.cpp.o
.PHONY : examples/tutorial/blas1.o

# target to build an object file
examples/tutorial/blas1.cpp.o:
	$(MAKE) -f CMakeFiles/blas1.dir/build.make CMakeFiles/blas1.dir/examples/tutorial/blas1.cpp.o
.PHONY : examples/tutorial/blas1.cpp.o

examples/tutorial/blas1.i: examples/tutorial/blas1.cpp.i
.PHONY : examples/tutorial/blas1.i

# target to preprocess a source file
examples/tutorial/blas1.cpp.i:
	$(MAKE) -f CMakeFiles/blas1.dir/build.make CMakeFiles/blas1.dir/examples/tutorial/blas1.cpp.i
.PHONY : examples/tutorial/blas1.cpp.i

examples/tutorial/blas1.s: examples/tutorial/blas1.cpp.s
.PHONY : examples/tutorial/blas1.s

# target to generate assembly for a file
examples/tutorial/blas1.cpp.s:
	$(MAKE) -f CMakeFiles/blas1.dir/build.make CMakeFiles/blas1.dir/examples/tutorial/blas1.cpp.s
.PHONY : examples/tutorial/blas1.cpp.s

examples/tutorial/custom-context.o: examples/tutorial/custom-context.cpp.o
.PHONY : examples/tutorial/custom-context.o

# target to build an object file
examples/tutorial/custom-context.cpp.o:
	$(MAKE) -f CMakeFiles/custom-context.dir/build.make CMakeFiles/custom-context.dir/examples/tutorial/custom-context.cpp.o
.PHONY : examples/tutorial/custom-context.cpp.o

examples/tutorial/custom-context.i: examples/tutorial/custom-context.cpp.i
.PHONY : examples/tutorial/custom-context.i

# target to preprocess a source file
examples/tutorial/custom-context.cpp.i:
	$(MAKE) -f CMakeFiles/custom-context.dir/build.make CMakeFiles/custom-context.dir/examples/tutorial/custom-context.cpp.i
.PHONY : examples/tutorial/custom-context.cpp.i

examples/tutorial/custom-context.s: examples/tutorial/custom-context.cpp.s
.PHONY : examples/tutorial/custom-context.s

# target to generate assembly for a file
examples/tutorial/custom-context.cpp.s:
	$(MAKE) -f CMakeFiles/custom-context.dir/build.make CMakeFiles/custom-context.dir/examples/tutorial/custom-context.cpp.s
.PHONY : examples/tutorial/custom-context.cpp.s

examples/tutorial/custom-kernels.o: examples/tutorial/custom-kernels.cpp.o
.PHONY : examples/tutorial/custom-kernels.o

# target to build an object file
examples/tutorial/custom-kernels.cpp.o:
	$(MAKE) -f CMakeFiles/custom-kernels.dir/build.make CMakeFiles/custom-kernels.dir/examples/tutorial/custom-kernels.cpp.o
.PHONY : examples/tutorial/custom-kernels.cpp.o

examples/tutorial/custom-kernels.i: examples/tutorial/custom-kernels.cpp.i
.PHONY : examples/tutorial/custom-kernels.i

# target to preprocess a source file
examples/tutorial/custom-kernels.cpp.i:
	$(MAKE) -f CMakeFiles/custom-kernels.dir/build.make CMakeFiles/custom-kernels.dir/examples/tutorial/custom-kernels.cpp.i
.PHONY : examples/tutorial/custom-kernels.cpp.i

examples/tutorial/custom-kernels.s: examples/tutorial/custom-kernels.cpp.s
.PHONY : examples/tutorial/custom-kernels.s

# target to generate assembly for a file
examples/tutorial/custom-kernels.cpp.s:
	$(MAKE) -f CMakeFiles/custom-kernels.dir/build.make CMakeFiles/custom-kernels.dir/examples/tutorial/custom-kernels.cpp.s
.PHONY : examples/tutorial/custom-kernels.cpp.s

examples/tutorial/viennacl-info.o: examples/tutorial/viennacl-info.cpp.o
.PHONY : examples/tutorial/viennacl-info.o

# target to build an object file
examples/tutorial/viennacl-info.cpp.o:
	$(MAKE) -f CMakeFiles/viennacl-info.dir/build.make CMakeFiles/viennacl-info.dir/examples/tutorial/viennacl-info.cpp.o
.PHONY : examples/tutorial/viennacl-info.cpp.o

examples/tutorial/viennacl-info.i: examples/tutorial/viennacl-info.cpp.i
.PHONY : examples/tutorial/viennacl-info.i

# target to preprocess a source file
examples/tutorial/viennacl-info.cpp.i:
	$(MAKE) -f CMakeFiles/viennacl-info.dir/build.make CMakeFiles/viennacl-info.dir/examples/tutorial/viennacl-info.cpp.i
.PHONY : examples/tutorial/viennacl-info.cpp.i

examples/tutorial/viennacl-info.s: examples/tutorial/viennacl-info.cpp.s
.PHONY : examples/tutorial/viennacl-info.s

# target to generate assembly for a file
examples/tutorial/viennacl-info.cpp.s:
	$(MAKE) -f CMakeFiles/viennacl-info.dir/build.make CMakeFiles/viennacl-info.dir/examples/tutorial/viennacl-info.cpp.s
.PHONY : examples/tutorial/viennacl-info.cpp.s

external/pugixml/src/pugixml.o: external/pugixml/src/pugixml.cpp.o
.PHONY : external/pugixml/src/pugixml.o

# target to build an object file
external/pugixml/src/pugixml.cpp.o:
	$(MAKE) -f CMakeFiles/matrixparams.dir/build.make CMakeFiles/matrixparams.dir/external/pugixml/src/pugixml.cpp.o
	$(MAKE) -f CMakeFiles/parameter_reader.dir/build.make CMakeFiles/parameter_reader.dir/external/pugixml/src/pugixml.cpp.o
	$(MAKE) -f CMakeFiles/sparseparams.dir/build.make CMakeFiles/sparseparams.dir/external/pugixml/src/pugixml.cpp.o
	$(MAKE) -f CMakeFiles/vectorparams.dir/build.make CMakeFiles/vectorparams.dir/external/pugixml/src/pugixml.cpp.o
.PHONY : external/pugixml/src/pugixml.cpp.o

external/pugixml/src/pugixml.i: external/pugixml/src/pugixml.cpp.i
.PHONY : external/pugixml/src/pugixml.i

# target to preprocess a source file
external/pugixml/src/pugixml.cpp.i:
	$(MAKE) -f CMakeFiles/matrixparams.dir/build.make CMakeFiles/matrixparams.dir/external/pugixml/src/pugixml.cpp.i
	$(MAKE) -f CMakeFiles/parameter_reader.dir/build.make CMakeFiles/parameter_reader.dir/external/pugixml/src/pugixml.cpp.i
	$(MAKE) -f CMakeFiles/sparseparams.dir/build.make CMakeFiles/sparseparams.dir/external/pugixml/src/pugixml.cpp.i
	$(MAKE) -f CMakeFiles/vectorparams.dir/build.make CMakeFiles/vectorparams.dir/external/pugixml/src/pugixml.cpp.i
.PHONY : external/pugixml/src/pugixml.cpp.i

external/pugixml/src/pugixml.s: external/pugixml/src/pugixml.cpp.s
.PHONY : external/pugixml/src/pugixml.s

# target to generate assembly for a file
external/pugixml/src/pugixml.cpp.s:
	$(MAKE) -f CMakeFiles/matrixparams.dir/build.make CMakeFiles/matrixparams.dir/external/pugixml/src/pugixml.cpp.s
	$(MAKE) -f CMakeFiles/parameter_reader.dir/build.make CMakeFiles/parameter_reader.dir/external/pugixml/src/pugixml.cpp.s
	$(MAKE) -f CMakeFiles/sparseparams.dir/build.make CMakeFiles/sparseparams.dir/external/pugixml/src/pugixml.cpp.s
	$(MAKE) -f CMakeFiles/vectorparams.dir/build.make CMakeFiles/vectorparams.dir/external/pugixml/src/pugixml.cpp.s
.PHONY : external/pugixml/src/pugixml.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... blas1"
	@echo "... blas3bench"
	@echo "... custom-context"
	@echo "... custom-kernels"
	@echo "... edit_cache"
	@echo "... matrixparams"
	@echo "... openclbench"
	@echo "... parameter_reader"
	@echo "... rebuild_cache"
	@echo "... sparseparams"
	@echo "... vectorbench"
	@echo "... vectorparams"
	@echo "... viennacl-info"
	@echo "... examples/benchmarks/blas3.o"
	@echo "... examples/benchmarks/blas3.i"
	@echo "... examples/benchmarks/blas3.s"
	@echo "... examples/benchmarks/opencl.o"
	@echo "... examples/benchmarks/opencl.i"
	@echo "... examples/benchmarks/opencl.s"
	@echo "... examples/benchmarks/vector.o"
	@echo "... examples/benchmarks/vector.i"
	@echo "... examples/benchmarks/vector.s"
	@echo "... examples/parameters/matrix.o"
	@echo "... examples/parameters/matrix.i"
	@echo "... examples/parameters/matrix.s"
	@echo "... examples/parameters/parameter_reader.o"
	@echo "... examples/parameters/parameter_reader.i"
	@echo "... examples/parameters/parameter_reader.s"
	@echo "... examples/parameters/sparse.o"
	@echo "... examples/parameters/sparse.i"
	@echo "... examples/parameters/sparse.s"
	@echo "... examples/parameters/vector.o"
	@echo "... examples/parameters/vector.i"
	@echo "... examples/parameters/vector.s"
	@echo "... examples/tutorial/blas1.o"
	@echo "... examples/tutorial/blas1.i"
	@echo "... examples/tutorial/blas1.s"
	@echo "... examples/tutorial/custom-context.o"
	@echo "... examples/tutorial/custom-context.i"
	@echo "... examples/tutorial/custom-context.s"
	@echo "... examples/tutorial/custom-kernels.o"
	@echo "... examples/tutorial/custom-kernels.i"
	@echo "... examples/tutorial/custom-kernels.s"
	@echo "... examples/tutorial/viennacl-info.o"
	@echo "... examples/tutorial/viennacl-info.i"
	@echo "... examples/tutorial/viennacl-info.s"
	@echo "... external/pugixml/src/pugixml.o"
	@echo "... external/pugixml/src/pugixml.i"
	@echo "... external/pugixml/src/pugixml.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

